name: android-tests
on:
    push:
        branches:
            - master
            - develop
jobs:
    android-unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
          
            # I Need to make gradlew executable
            - name: Make gradlew executable
              working-directory: ./AndroidProject
              run: chmod +x ./gradlew
          
            # Execute unit tests
            - name: Android units tests
              working-directory: ./AndroidProject
              env:
                GITHUB_TOKEN: ${{ secrets.TOKEN }}
              run: ./gradlew clean jacocoTestReport sonarqube
              
            # Show a report of the unit tests results
            - name: Android Test Report
              uses: asadmansr/android-test-report-action@v1.2.0
              if: ${{ always() }} # IMPORTANT: run Android Test Report regardless


    android-integration-tests:
        runs-on: macos-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                java-version: 11
          
            # I Need to make gradlew executable
            - name: Make gradlew executable
              working-directory: ./AndroidProject
              run: chmod +x ./gradlew
          
            # Integration Tests
            - name: Android UI tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                api-level: 27  # api level > 27 seems to be failing at sdk installation step
                working-directory: ./AndroidProject
                profile: pixel_2
                target: google_apis
                script: ./gradlew connectedCheck
                
            - name: Android UI tests artifacts
              uses: actions/upload-artifact@v2
              with:
                name: ui-tests-artifacts
                path: ./AndroidProject/app/build/reports/androidTests/connected/index.html
                
    # android-release-apk:
        # needs: [android-unit-tests, android-integration-tests]
        # runs-on: ubuntu-latest
        # steps:
            # - name: checkout
              # uses: actions/checkout@v2
          
            # # I Need to make gradlew executable
            # - name: Make gradlew executable
              # working-directory: ./AndroidProject
              # run: chmod +x ./gradlew
              
            # - name: Build Release APK
              # working-directory: ./AndroidProject
              # run: ./gradlew assembleDebug
            
            # - name: Create Release
              # id: create_release
              # uses: actions/create-release@v1
              # env:
                # GITHUB_TOKEN: ${{ secrets.TOKEN }} 
              # with:
                # tag_name: v.${{ github.run_id }}
                # release_name: Release ${{ github.id }} 
          
            # - name: Upload Release APK
              # id: upload_release_asset
              # uses: actions/upload-release-asset@v1.0.1
              # env:
                # GITHUB_TOKEN: ${{ secrets.TOKEN }}
              # with:
                  # upload_url: ${{ steps.create_release.outputs.upload_url }}
                  # asset_path: ./AndroidProject/app/build/outputs/apk/debug/app-debug.apk
                  # asset_name: ociosantander.apk
                  # asset_content_type: application/zip
        
